sakinah_saudi_female:
  preparation: true
  video_path: /avatars/source/sakinah-saudi-female-idle.mp4
  audio_clips:
    test: /avatars/audio/test-arabic.wav

sakinah_uk_female:
  preparation: true
  video_path: /avatars/source/sakinah-uk-female-idle.mp4
  audio_clips:
    test: /avatars/audio/test-english.wav
